added the chance to download all the packages

diff --git a/src/bin/storm-download-rpm b/src/bin/storm-download-rpm
--- a/src/bin/storm-download-rpm
+++ b/src/bin/storm-download-rpm
@@ -22,9 +22,12 @@ function usage() {
    echo
    echo "Example: storm-download-rpm storm-backend-server"
    echo "       : storm-download-rpm -U storm-backend-server"
+   echo "       : storm-download-rpm -U"
+   echo "       : storm-download-rpm -A"
    echo
    echo "OPTIONS:"
    echo "        -U,  --update: updates the list of available packages"
+   echo "        -A,  --all: downloads all available packages"
    echo "        -h,  --help: prints this help message"
    echo
    if [  ! -f $PACKAGES_FILE  ] || [ ! -s $PACKAGES_FILE ] ; then
@@ -47,6 +50,43 @@ function extractGreaterVersion(){
    return 0
 }
 
+function downloadPackage(){
+   if [ $# -lt 1 ]; then
+      echo "Internal error, expected RPM_NAME, got: $@"
+      return 1
+   fi
+   PACKAGE_NAME=$1
+   grep $PACKAGE_NAME $PACKAGES_FILE &> /dev/null
+   if [ ! 0 -eq $? ]; then
+      echo "Package -${PACKAGE_NAME}- unknown. Try to update packages using \"-U\" Option"
+      return 2
+   fi
+   curl -X GET http://storm.forge.cnaf.infn.it/repository/rpm_repository/ 2>/dev/null | tr ' ' '\n' | tr '"' '\n' | grep rpm | grep -v 'src\.rpm' | grep $PACKAGE_NAME | grep sl${osdist} > $TEMP_FILE
+   curl -X GET http://storm.forge.cnaf.infn.it/repository/rpm_repository/ 2>/dev/null | tr ' ' '\n' | tr '"' '\n' | grep rpm | grep -v 'src\.rpm' | grep $PACKAGE_NAME | grep el${osdist} >> $TEMP_FILE
+   RPM_NAME=$(cat $TEMP_FILE | sed 's/<\/a>//g' | sed 's/<a>//g' | tr -d '<>')
+   rm -f $TEMP_FILE
+   if test $(echo $RPM_NAME | wc -w) -gt 1 ; then
+      extractGreaterVersion $RPM_NAME "FINAL_RPM_NAME"
+   else
+      FINAL_RPM_NAME=$RPM_NAME
+   fi
+   echo "Downloading $FINAL_RPM_NAME"
+   curl http://storm.forge.cnaf.infn.it/repository/rpm_repository/$FINAL_RPM_NAME -o $FINAL_RPM_NAME &> /dev/null
+   return 0
+}
+
+
+function downloadAll(){
+   if [  ! -f $PACKAGES_FILE  ] || [ ! -s $PACKAGES_FILE ] ; then
+      updatePackages
+   fi
+   for RPM_NAME in $(cat $PACKAGES_FILE); do
+      downloadPackage $RPM_NAME
+   done
+   rm -f $TEMP_FILE
+}
+
+
 
 if [ $# -lt 1 ]; then
    usage
@@ -65,6 +105,15 @@ if [ $1 == "-U" -o $1 == "--update" ]; then
       exit 0
    fi
    PACKAGE_NAME=$2
+elif [ $1 == "-A" -o $1 == "--all" ]; then
+   if [ $# -gt 1 ]; then
+      echo "Invalid arguments after -A/-all option"
+      usage
+      exit 1
+   fi
+   updatePackages
+   downloadAll
+   exit 0
 else
    PACKAGE_NAME=$1
 fi
@@ -74,20 +123,5 @@ if [ -z $PACKAGE_NAME ]; then
 fi
 
 
-grep $PACKAGE_NAME $PACKAGES_FILE &> /dev/null
-if [ ! 0 -eq $? ]; then
-   echo "Package unknown. Try to update packages using \"-U\" Option"
-   usage
-   exit 2
-fi
-curl -X GET http://storm.forge.cnaf.infn.it/repository/rpm_repository/ 2>/dev/null | tr ' ' '\n' | tr '"' '\n' | grep rpm | grep -v 'src\.rpm' | grep $PACKAGE_NAME | grep sl${osdist} > $TEMP_FILE
-curl -X GET http://storm.forge.cnaf.infn.it/repository/rpm_repository/ 2>/dev/null | tr ' ' '\n' | tr '"' '\n' | grep rpm | grep -v 'src\.rpm' | grep $PACKAGE_NAME | grep el${osdist} >> $TEMP_FILE
-RPM_NAME=$(cat $TEMP_FILE | sed 's/<\/a>//g' | sed 's/<a>//g' | tr -d '<>')
-rm -f $TEMP_FILE
-if test $(echo $RPM_NAME | wc -w) -gt 1 ; then
-   extractGreaterVersion $RPM_NAME "FINAL_RPM_NAME"
-else
-   FINAL_RPM_NAME=$RPM_NAME
-fi
-curl http://storm.forge.cnaf.infn.it/repository/rpm_repository/$FINAL_RPM_NAME -o $FINAL_RPM_NAME &> /dev/null
-exit 0
+downloadPackage $PACKAGE_NAME
+exit $?
